### ISSUE TITLE
"TypeError: Assignment to constant variable." while "node debug.js"

### ISSUE THREAD

**Issue by osenvosem** [totaljs/cms#1]
```
----------------------------------------------------> PID: 970 (v4.0)
TypeError: Assignment to constant variable.
    at restart (/Users/srg/Documents/dev/three/debug.js:11:2250)
    at app (/Users/srg/Documents/dev/three/debug.js:11:3687)
    at run (/Users/srg/Documents/dev/three/debug.js:11:3914)
    at Object.<anonymous> (/Users/srg/Documents/dev/three/debug.js:11:4183)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

**Comment by petersirka** [comment]
Hi @osenvosem,
thank you, I have fixed it. Can you test it again?

**Comment by osenvosem** [comment]
Ok, now it works.

**Comment by petersirka** [comment]
Great! Thank you.
