### ISSUE TITLE
running debug.js error

### ISSUE THREAD

**Issue by assiomatica** [totaljs/cms#8]
```
node debug.js
-------------------------> DEBUG PID: 26915 (v2.9.2)
[TypeError: stream.prependListener is not a function]
======= 2018-01-31 06:54:57: TypeError: stream.prependListener is not a function TypeError: stream.prependListener is not a function
    at onFinished (/root/youpitchme/cms/node_modules/total.js/internal.js:3147:10)
    at global.WTF.global.NOBIN.global.NOCOUNTER.global.NOMEM.global.CONFIG.global.UPTODATE.global.INSTALL.global.UNINSTALL.global.RESOURCE.global.TRANSLATE.global.TRANSLATOR.global.TRACE.global.$$$.global.CREATE.global.SCRIPT.global.SINGLETON.global.FUNCTION.global.ROUTING.global.SCHEDULE.global.ROUTE.global.GROUP.global.WEBSOCKET.global.FILE.global.REDIRECT.global.CLEANUP (/root/youpitchme/cms/node_modules/total.js/index.js:436:2)
    at Database.emit.Database.removeListener.Database.$reader2 (/root/youpitchme/cms/node_modules/total.js/nosql.js:1204:3)
    at Database.emit.Database.removeListener.Database.$reader (/root/youpitchme/cms/node_modules/total.js/nosql.js:994:8)
    at Database.emit.Database.removeListener.Database.next (/root/youpitchme/cms/node_modules/total.js/nosql.js:576:8)
    at Immediate.next_operation (/root/youpitchme/cms/node_modules/total.js/nosql.js:233:7)
    at Immediate.immediate._onImmediate (timers.js:445:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
[TypeError: stream.prependListener is not a function]
======= 2018-01-31 06:54:57: TypeError: stream.prependListener is not a function TypeError: stream.prependListener is not a function
    at onFinished (/root/youpitchme/cms/node_modules/total.js/internal.js:3147:10)
    at global.WTF.global.NOBIN.global.NOCOUNTER.global.NOMEM.global.CONFIG.global.UPTODATE.global.INSTALL.global.UNINSTALL.global.RESOURCE.global.TRANSLATE.global.TRANSLATOR.global.TRACE.global.$$$.global.CREATE.global.SCRIPT.global.SINGLETON.global.FUNCTION.global.ROUTING.global.SCHEDULE.global.ROUTE.global.GROUP.global.WEBSOCKET.global.FILE.global.REDIRECT.global.CLEANUP (/root/youpitchme/cms/node_modules/total.js/index.js:436:2)
    at Database.emit.Database.removeListener.Database.$reader2 (/root/youpitchme/cms/node_modules/total.js/nosql.js:1204:3)
    at Database.emit.Database.removeListener.Database.$reader (/root/youpitchme/cms/node_modules/total.js/nosql.js:994:8)
    at Database.emit.Database.removeListener.Database.next (/root/youpitchme/cms/node_modules/total.js/nosql.js:576:8)
    at Immediate.next_operation (/root/youpitchme/cms/node_modules/total.js/nosql.js:233:7)
    at Immediate.immediate._onImmediate (timers.js:445:18)
    at processImmediate (timers.js:383:17)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
[TypeError: stream.prependListener is not a function]
======= 2018-01-31 06:54:57: TypeError: stream.prependListener is not a function TypeError: stream.prependListener is not a function
    at onFinished (/root/youpitchme/cms/node_modules/total.js/internal.js:3147:10)
    at global.WTF.global.NOBIN.global.NOCOUNTER.global.NOMEM.global.CONFIG.global.UPTODATE.global.INSTALL.global.UNINSTALL.global.RESOURCE.global.TRANSLATE.global.TRANSLATOR.global.TRACE.global.$$$.global.CREATE.global.SCRIPT.global.SINGLETON.global.FUNCTION.global.ROUTING.global.SCHEDULE.global.ROUTE.global.GROUP.global.WEBSOCKET.global.FILE.global.REDIRECT.global.CLEANUP (/root/youpitchme/cms/node_modules/total.js/index.js:436:2)
    at Database.emit.Database.removeListener.Database.$reader2 (/root/youpitchme/cms/node_modules/total.js/nosql.js:1204:3)
    at Database.emit.Database.removeListener.Database.$reader (/root/youpitchme/cms/node_modules/total.js/nosql.js:994:8)
    at Database.emit.Database.removeListener.Database.next (/root/youpitchme/cms/node_modules/total.js/nosql.js:576:8)
    at Immediate.next_operation (/root/youpitchme/cms/node_modules/total.js/nosql.js:233:7)
    at Immediate.immediate._onImmediate (timers.js:445:18)
    at processImmediate (timers.js:383:17)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
====================================================
PID         : 26920
Node.js     : v4.2.6
Total.js    : v2.9.2
OS          : linux 4.4.0-109-generic
====================================================
Name        : CMS
Version     : 8.0.0
Author      : Peter Širka
Date        : 2018-01-31 06:54:57
Mode        : debug
====================================================

http://0.0.0.0:8000/

```

**Comment by molda** [comment]
Hi @assiomatica You need Node.js version 6 or higher.

**Comment by assiomatica** [comment]
Oh , I see ! Thanks

On 31/01/2018, Martin Smola <notifications@github.com> wrote:
> Hi @assiomatica You need Node.js version 6 or higher.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/totaljs/cms/issues/8#issuecomment-361843358


-- 
Antonio Casula

mobile ch   +41 (0)79 9692274

   - ch.linkedin.com/in/antoniocasula/
